"""
Django settings for MeetSureBackEnd project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import requests
import firebase_admin
from firebase_admin import credentials, firestore, initialize_app

OPENAI_API_KEY = "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"
import firebase_admin
from firebase_admin import credentials, firestore, initialize_app

OPENAI_API_KEY = "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"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# 設定 Firebase JSON 憑證路徑
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, "MeetSureBackEnd", "meetsure-new-firebase-adminsdk-fbsvc-b3b700a86d.json")

if not firebase_admin._apps:
    cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
    firebase_app = initialize_app(cred)
    db = firestore.client()
# time_zone
USE_TZ = True
TIME_ZONE = 'Asia/Taipei'# 設定 Firebase JSON 憑證路徑
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, "MeetSureBackEnd", "meetsure-new-firebase-adminsdk-fbsvc-b3b700a86d.json")

if not firebase_admin._apps:
    cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
    firebase_app = initialize_app(cred)
    db = firestore.client()


try:
    import torch
    print("✅ PyTorch is available!")
except ImportError:
    torch = None
    print("❌ PyTorch is not installed.")

try:
    import tensorflow as tf
    print("✅ TensorFlow is available!")
except ImportError:
    tf = None
    print("❌ TensorFlow is not installed.")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ek!s2xb@ztk&2-o_29j(@72c7*0xs_4ycy=5hl5osm@y8c^ptm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

OPENAI_API_KEY=[]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  
    'myapp',
    'corsheaders',
    'transcriber'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
ROOT_URLCONF = 'MeetSureBackEnd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '../MeetSureFrontEnd/build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MeetSureBackEnd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'MeetSure',  # 資料庫名稱
        'USER': 'postgres',  # 資料庫用戶
        'PASSWORD': '12345678',  # 資料庫密碼
        'HOST': 'localhost',  # 或資料庫所在的伺服器位址
        'PORT': '5432',  # PostgreSQL 默認端口號
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # 你的前端地址
    'http://127.0.0.1:8000',
]
CORS_ALLOW_CREDENTIALS = True  # 允許傳遞 cookie


CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',  # 前端地址
    "https://meetsure-new.web.app",
]

CSRF_COOKIE_SECURE = False  # 在開發環境中應為 False
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']  # 允許的來源



ALLOWED_HOSTS = ["*"]  # 允許所有主機訪問，適合開發時使用


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py

STATIC_URL = '/static/'

# 指向 React 的 build/static 資料夾
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '../MeetSureFrontEnd/build/static'),  
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def get_ngrok_url():
    try:
        response = requests.get("http://localhost:4040/api/tunnels")
        response.raise_for_status()
        tunnels = response.json().get("tunnels", [])  # 避免 tunnels 為 None
        for tunnel in tunnels:
            if tunnel.get("proto") == "https":  # 只取 HTTPS
                return tunnel.get("public_url")
    except requests.exceptions.RequestException:
        return None

NGROK_URL = get_ngrok_url()
if NGROK_URL:
    CORS_ALLOWED_ORIGINS.append(NGROK_URL)  # ✅ 自動加入 ngrok 網址
if NGROK_URL:
    CSRF_TRUSTED_ORIGINS.append(NGROK_URL)  # ✅ ngrok URL 需要完整格式
    print(f"更新 CSRF_TRUSTED_ORIGINS: {CSRF_TRUSTED_ORIGINS}")
    
print(f"CORS 允許的來源: {CORS_ALLOWED_ORIGINS}")  # ✅ 確保終端機能看到允許的網址
print(f"🔍 取得的 NGROK_URL: {NGROK_URL}")  # 🛑 在啟動時顯示 NGROK_URL

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")