# Generated by Django 5.1.2 on 2025-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linebinding",
            name="verification_code",
            field=models.CharField(default="b06a75", max_length=6, unique=True),
        ),
    ]
