# Generated by Django 5.1.1 on 2025-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_linebinding_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='c8af2c', max_length=6, unique=True),
        ),
    ]
