# Generated by Django 5.1.1 on 2025-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_linebinding_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='52478b', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='line_user_id',
            field=models.CharField(max_length=50),
        ),
    ]
