# Generated by Django 5.1.2 on 2025-03-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_linebinding_verification_code"),
        ("myapp", "0006_alter_friend_user1_alter_friend_user2_and_more"),
    ]

    operations = []
