# Generated by Django 5.1.1 on 2025-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_linebinding_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='linebinding',
            name='is_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='718f23', max_length=6, null=True, unique=True),
        ),
    ]
