# Generated by Django 5.1.2 on 2025-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_linebinding_verification_code_meetingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='443dd8', max_length=6, unique=True),
        ),
    ]
