# Generated by Django 5.1.1 on 2025-03-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_friend_user1_alter_friend_user2_and_more'),
        ('myapp', '0009_linebinding_is_linked_and_more'),
    ]

    operations = [
    ]
