# Generated by Django 5.1.1 on 2025-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20250320_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='6266dd', max_length=6, null=True, unique=True),
        ),
    ]
