# Generated by Django 5.1.2 on 2025-03-22 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_linebinding_verification_code_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='195fa9', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
