# Generated by Django 5.1.1 on 2025-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_linebinding_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(default='19e89c', max_length=6, null=True, unique=True),
        ),
    ]
