# Generated by Django 5.1.2 on 2025-03-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_linebinding_is_linked_and_more'),
        ('myapp', '0013_alter_linebinding_verification_code_meetingrecord'),
    ]

    operations = [
    ]
