# Generated by Django 5.1.1 on 2025-03-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_meetingschedule_updated_at_and_more'),
        ('myapp', '0013_add_friendrequest_table'),
    ]

    operations = [
    ]
