# Generated by Django 5.1.1 on 2025-03-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20250321_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(blank=True, default='645b17', max_length=6, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MeetingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=255)),
                ('meeting_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
