# Generated by Django 5.1.1 on 2025-03-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_linebinding_verification_code_and_more'),
        ('myapp', '0015_alter_linebinding_verification_code_and_more'),
    ]

    operations = [
    ]
