# Generated by Django 5.1.1 on 2025-03-23 14:30

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_merge_20250323_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(blank=True, default=myapp.models.generate_code, max_length=6, null=True, unique=True),
        ),
    ]
