# Generated by Django 5.1.2 on 2025-03-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_project_alter_linebinding_verification_code_and_more"),
        ("myapp", "0017_alter_linebinding_verification_code"),
    ]

    operations = []
