# Generated by Django 5.1.2 on 2025-03-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_merge_20250327_0245'),
        ('myapp', '0017_alter_linebinding_verification_code'),
    ]

    operations = [
    ]
