# Generated by Django 5.1.2 on 2025-03-27 11:32

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_merge_20250327_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linebinding',
            name='verification_code',
            field=models.CharField(blank=True, default=myapp.models.generate_code, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='myapp.users'),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='myapp.project'),
        ),
        migrations.AlterModelTable(
            name='friend',
            table='friend',
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='friendrequest',
        ),
        migrations.AlterModelTable(
            name='meetingschedule',
            table='meetingschedule',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
            options={
                'db_table': 'group_memberships',
            },
        ),
    ]
