# Generated by Django 5.1.2 on 2025-04-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_linebinding_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to='myapp.users'),
            preserve_default=False,
        ),
    ]
