# Generated by Django 5.1.2 on 2025-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_group_created_at_groupmembership_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('project', '專案群組'), ('custom', '自創群組')], default='custom', max_length=20),
        ),
    ]
