# Generated by Django 5.1.2 on 2025-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='is_admin',
        ),
    ]
