# Generated by Django 5.1.2 on 2025-04-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_gantttask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
