# Generated by Django 5.1.1 on 2025-04-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_delete_meeting_alter_project_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
